### ISSUE TITLE
Happybase pool connection with pool.apply_async.

### ISSUE THREAD

**Issue by arfaoui47** [wbolster/happybase#124]
I'm using happybase.ConnectionPool to reuse connection for asynchronous call of functions that are using hbase. The first attempt always return error ("Unexpected TType") which is an error from Thrift server but, then the async call passes. Using only connection make the async call always fail with same error ("Unexpected TType").

**Comment by wbolster** [comment]
which pool? multiprocessing? does each process have its own private connection?

**Comment by arfaoui47** [comment]
I have a list of functions which are call asynchronously (Pool.apply_async from multiprocessing library)
these functions also retrieve data from hbase.
First, I make a call for

> `pool = happybase.ConnectionPool(size=100,`  host=host, port=int(port), ble_prefix=prefix)`

then I run these functions asynchronously where I obtain a connection from the pool using:
`with self.pool.connection() as connection:`
`    #process data`

**Comment by wbolster** [comment]
processes cannot meaningfully share connections (standard unix stuff, nothing happybase specific), so each child process needs to instantiate its own pool when spawned. those pools can have size=1, but il that number doesn't really matter since a single thread cannot obtain more than one connection anyway.

**Comment by arfaoui47** [comment]
Thank you problem solved. I wasn't declaring pool in constructor.
