### ISSUE TITLE
cannot connect to my hbase cluster

### ISSUE THREAD

**Issue by Tracy6465** [wbolster/happybase#169]
Traceback (most recent call last):
  File "/home/chris/hbase/hbaseDemo.py", line 5, in <module>
    connection = happybase.Connection(host='99.12.136.116,99.12.230.86,99.12.232.57', port=2181)
  File "/home/chris/.local/lib/python2.7/site-packages/happybase/connection.py", line 148, in __init__
    self.open()
  File "/home/chris/.local/lib/python2.7/site-packages/happybase/connection.py", line 176, in open
    self.transport.open()
  File "thriftpy/transport/buffered/cybuffered.pyx", line 34, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.open (thriftpy/transport/buffered/cybuffered.c:1383)
  File "/home/chris/.local/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 104, in open
    message="Could not connect to %s" % str(addr))
thriftpy.transport.TTransportException: TTransportException(message="Could not connect to ('99.12.136.116,99.12.230.86,99.12.232.57', 2181)", type=1)

hbase version is 1.2.4

**Comment by wbolster** [comment]
hi @Tracy6465,

`<sarcasm>`

_thank you so much_ for writing such a friendly bug report. it is _very clear_ you actually invested effort instead of just dumping a random stack trace into my bug tracker without any explanation.

`</sarcasm>`

first, i really _hate_ this type of bug reports. you dump an error message, demand my attention, but you did not even _explain_ anything. no courtesy, just an implicit message that sounds like "hey you, fix my problem" to me. you are not my customer. if anything, it's the other way around. i would advise you to keep that in mind instead of passive-aggressively demanding my attention and free consultancy.

anyway, that said.

> `port=2181`

do you run thrift daemons (typically those use a different port)?  happybase only talks to thrifs daemons. as explained in the docs.

**Comment by DachuanZhao** [comment]
> hi @Tracy6465,
> 
> `<sarcasm>`
> 
> _thank you so much_ for writing such a friendly bug report. it is _very clear_ you actually invested effort instead of just dumping a random stack trace into my bug tracker without any explanation.
> 
> `</sarcasm>`
> 
> first, i really _hate_ this type of bug reports. you dump an error message, demand my attention, but you did not even _explain_ anything. no courtesy, just an implicit message that sounds like "hey you, fix my problem" to me. you are not my customer. if anything, it's the other way around. i would advise you to keep that in mind instead of passive-aggressively demanding my attention and free consultancy.
> 
> anyway, that said.
> 
> > `port=2181`
> 
> do you run thrift daemons (typically those use a different port)? happybase only talks to thrift daemons. as explained in the docs.

How to connect hbase cluster by ```happybase``` ?
